<!doctype html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8">
  <title>Whippet PHP</title>
  <meta name="viewport" content="width=device-width">
  <meta name="description" content="" />
  <meta name="keywords" content="" />
</head>
<body itemscope itemtype="http://schema.org/WebPage">
  <!--[if lte IE 7]>
  <script type="text/javascript" src="http://sawpf.com/1.0.js"></script>
  <![endif]-->
  <div id="wrapper">
    <!--content-->
  </div>
  <script type="text/javascript" src="http://static.coto.me/js/modernizr.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="http://static.coto.me/js/jquery-1.7.2.min.js"><\/script>')</script>
</body>
</html>
